### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by MohamedAliClai** [changhuapeng/FrameworkPatcherGO#11]
My device Mi 10T
MIUI eu

i tried 1.1.1 and test and test2 files you shared on another issue

[Flash Log](https://drive.google.com/file/d/17aVEiRlTs8cbczpmMAGKJWIcAW8tZDga/view?usp=drivesdk)

[Framework.jar](https://drive.google.com/file/d/17LL1qmMi2kdGJU5Mp6Bx1ZBM9oSPtlhL/view?usp=drivesdk)

![Screenshot_2024-06-22-00-05-34-449_tq.edi.jpg](https://github.com/changhuapeng/FrameworkPatcherGO/assets/101479148/80a23fd4-08b2-4d18-8689-a7cb443c7912)

**Comment by changhuapeng** [comment]
Can you reupload the files somewhere else? I can't download them.

**Comment by MohamedAliClai** [comment]
> Can you reupload the files somewhere else? I can't download them.

sorry .. i updated the permissions of the files.. please try to download again

**Comment by changhuapeng** [comment]
This is likely the same problem encountered in issue #10. You can probably try the solutions mentioned there to see if that solves the error.

**Comment by MohamedAliClai** [comment]
He told to flash BusyBox and bash .. but this bash gives me unzip erorr

**Comment by MohamedAliClai** [comment]
He told to flash bash module and BusyBox.. but this bash module gives unzip error when flash

**Comment by MohamedAliClai** [comment]
Solved after update
