### ISSUE TITLE
Question on Uninstall

### ISSUE THREAD

**Issue by Djtrip83** [changhuapeng/FrameworkPatcherGO#21]
Does uninstalling and removing this module via Magisk restore original files or settings, or do we need to remove some files manually? Thanks for the info. Just asking since PlayIntegrity Fix started not working, and is still the case after uninstalling FrameworkPatcher and running a clean re-install of PlayIntegrity Fix.

**Comment by Star-Seven** [comment]
Just uninstall the module.

**Comment by changhuapeng** [comment]
> Does uninstalling and removing this module via Magisk restore original files or settings, or do we need to remove some files manually? Thanks for the info. Just asking since PlayIntegrity Fix started not working, and is still the case after uninstalling FrameworkPatcher and running a clean re-install of PlayIntegrity Fix.

Uninstalling this module will revert any systemless changes made by the module and you do not need to remove any files manually. The issue that you were facing with PlayIntegrityFix is not related to this module.

Hope this helps.
