### ISSUE TITLE
The module did not install properly.

### ISSUE THREAD

**Issue by NingLing520** [changhuapeng/FrameworkPatcherGO#3]
magisk:kitsune mask
magisk version:R65C33E4F-kitsune mask(27001)
Phone model: Redmi K40 Gaming(aras)
system version:MIUI 13 22.10.25 Dev
Kernel version:4.14.186-g89d850276fb2

When I was installing the module, Magisk's log directly returned a failure to install.

**Comment by changhuapeng** [comment]
Can you provide the installation log?

**Comment by NingLing520** [comment]
[Uploading magisk_install_log_2024-06-06T07.20.17.log…]()

**Comment by changhuapeng** [comment]
The log is not uploaded properly.

**Comment by NingLing520** [comment]
![Screenshot_2024-06-06-20-00-35-379_bin mt plus](https://github.com/changhuapeng/FrameworkPatcherGO/assets/89759843/fd230031-2598-46a7-ab32-b0fa1c313a18)

**Comment by changhuapeng** [comment]
Probably might need some time with this issue. So far, I'm still able to reproduce the error on my phone with Magisk Kitsune 27001.

**Comment by changhuapeng** [comment]
Please test v1.1.0 to see if it solves the error that you encountered.
