### ISSUE TITLE
[Error] keycheck

### ISSUE THREAD

**Issue by Nep-Timeline** [changhuapeng/FrameworkPatcherGO#4]
"error: keycheck" error occurred, causing the module to be unable to install
Using Magisk Alpha c6f07625 (27002)

**Comment by changhuapeng** [comment]
Is the device that you're installing on not have any volume keys?

The module installation script requires volume keys for user input, so the error that you're encountered was during the script check for presence of volume keys.

**Comment by Nep-Timeline** [comment]
> Is the device that you're installing on not have any volume keys?
> 
> The module installation script requires volume keys for user input, so the error that you're encountered was during the script check for presence of volume keys.

no, the problem occurred after I pressed the volume key

**Comment by changhuapeng** [comment]
Can you try if this version is working for you?

[FrameworkPatcherGO-v1.0.0-test.zip](https://github.com/user-attachments/files/15751498/FrameworkPatcherGO-v1.0.0-test.zip)
