### ISSUE TITLE
Error patchinginstrumentation.smali - FrameworkPatcherGO-v1.0.1

### ISSUE THREAD

**Issue by ogromanas** [changhuapeng/FrameworkPatcherGO#5]
android_14.0.0-r35
Voltage os 3.4
MANUFACTURER": "Xiaomi",
"MODEL": "Redmi Note 10 Pro",
"FINGERPRINT": "Redmi/sweet_eea/sweet:13/RKQ1.210614.002/V14.0.9.0.TKFEUXM:user/release-keys",

[******************************
> Patching Instrumentation.smali file ...
******************************
Method found: .method public static whitelist newApplication(Ljava/lang/Class;Landroid/content/Context;)Landroid/app/Application;
Context register not found in newApplication static method
 Mounting:auto:ro:1: /dev/block/dm-4 /system_ext
 Mounting:auto:ro:1: /dev/block/dm-1 /vendor
 Mounting:auto:ro:1: /dev/block/dm-2 /product
 Mounting:auto:ro:1: /dev/block/dm-3 /odm
- Error: Failed to install module script
Error: Failed to install module script

KernelSU_install_log_2024-06-10-09-13-04.log](https://github.com/user-attachments/files/15758057/KernelSU_install_log_2024-06-10-09-13-04.log)

**Comment by changhuapeng** [comment]
Can you try this?
[FrameworkPatcherGO-v1.0.1-test.zip](https://github.com/user-attachments/files/15774703/FrameworkPatcherGO-v1.0.1-test.zip)

**Comment by ogromanas** [comment]
Now, it seems that the installation is correct according to the log. But on reboot, the system does not boot and stays in the boot logo. I clean the cache and dalvik-cache, the system reboots now. But if I go into kernelsu, the module does not appear. As if it was not installed. If I check /data/adb/modules there is no trace of the installation. If I install it again (it still gives me a successful installation), before rebooting, I check /data/adb and /data/adb/modules/ and it still doesn't appear. 

[KernelSU_install_log_2024-06-10-17-11-32.log](https://github.com/user-attachments/files/15775628/KernelSU_install_log_2024-06-10-17-11-32.log)
[KernelSU_install_log_2024-06-10-17-20-04.log](https://github.com/user-attachments/files/15775629/KernelSU_install_log_2024-06-10-17-20-04.log)

**Comment by ogromanas** [comment]
With the second installation and subsequent reboot. No need to clean cache and dalvik cache. The module does appear.

In keyattestation app comes out this:

I use microg, CTS fail basic. Cts profile does not match

![Screenshot_20240610-173903](https://github.com/changhuapeng/FrameworkPatcherGO/assets/2190247/4fd65743-93dd-4ed4-a11f-c1100caeb1e8)

**Comment by ogromanas** [comment]
/data/adb/modules/FrameworkPatcherGo

[FrameworkPatcherGo.zip](https://github.com/user-attachments/files/15775911/FrameworkPatcherGo.zip)

**Comment by changhuapeng** [comment]
Your modified framwork.jar looks good and the patches are being applied properly.

Honestly, I'm not too knowledgeable about microG to provide a solution but since you're using PIF already, are you able to pass DEVICE integrity with that module?

**Comment by changhuapeng** [comment]
> Can you try this? [FrameworkPatcherGO-v1.0.1-test.zip](https://github.com/user-attachments/files/15774703/FrameworkPatcherGO-v1.0.1-test.zip)

Firstly, I'm closing this issue to mark it resolved since you're able to install the module successfully after this particular fix.

Secondly, please read q.6 in the [FAQ](https://xdaforums.com/t/module-framework-patcher-go.4674536/#post-89539511) and see if the mentioned solutions help with your CTS or Play Integrity problem.
