### ISSUE TITLE
Failed to install module script when patching Instrumentation (APatch)

### ISSUE THREAD

**Issue by CDzungx** [changhuapeng/FrameworkPatcherGO#9]
Using APatch 10844
FPG 1.1.1
Framework.jar: [File](https://mega.nz/file/1yYkwByb#QdOUUQOuVj9zWZBTmmf6Pux_ecX86bdSZuZBzkZwDlU)
![Screenshot_2024-06-19-01-37-31-220_me bmax apatch-edit](https://github.com/changhuapeng/FrameworkPatcherGO/assets/59353870/0ad3c668-7db7-42e5-9863-d70ef7a8ce32)

**Comment by changhuapeng** [comment]
Please provide your `framework.jar` so I can troubleshoot it when I have the time. You can look at the FAQs in my XDA thread if you need the instructions for that.

**Comment by CDzungx** [comment]
> Please provide your `framework.jar` so I can troubleshoot it when I have the time. You can look at the FAQs in my XDA thread if you need the instructions for that.

Added ;)

**Comment by changhuapeng** [comment]
@CDzungx @Sucharek233 Please try this test version: [FrameworkPatcherGO-v1.1.1-test.zip](https://github.com/user-attachments/files/15903724/FrameworkPatcherGO-v1.1.1-test.zip)

**Comment by CDzungx** [comment]
> @CDzungx @Sucharek233 Please try this test version: [FrameworkPatcherGO-v1.1.1-test.zip](https://github.com/user-attachments/files/15903724/FrameworkPatcherGO-v1.1.1-test.zip)

Seem to work but now is another err when patching APM 
![Uploading Screenshot_2024-06-20-01-31-51-004_me.bmax.apatch-edit.jpg…]()

**Comment by changhuapeng** [comment]
> Seem to work but now is another err when patching APM

Try this: [FrameworkPatcherGO-v1.1.1-test2.zip](https://github.com/user-attachments/files/15904878/FrameworkPatcherGO-v1.1.1-test2.zip)

**Comment by CDzungx** [comment]
> > Seem to work but now is another err when patching APM
> 
> Try this: [FrameworkPatcherGO-v1.1.1-test2.zip](https://github.com/user-attachments/files/15904878/FrameworkPatcherGO-v1.1.1-test2.zip)

This file err in Instrumental again, same with first pic

**Comment by changhuapeng** [comment]
> This file err in Instrumentation again, same with first pic

My bad, uploaded the wrong file. This is the right one.
[FrameworkPatcherGO-v1.1.1-test2.zip](https://github.com/user-attachments/files/15904961/FrameworkPatcherGO-v1.1.1-test2.zip)

**Comment by CDzungx** [comment]
> > This file err in Instrumentation again, same with first pic
> 
> My bad, uploaded the wrong file. This is the right one. [FrameworkPatcherGO-v1.1.1-test2.zip](https://github.com/user-attachments/files/15904961/FrameworkPatcherGO-v1.1.1-test2.zip)

Flashed successfull, on first boot it seem to stuck on boot screen, I have to shutdown and boot again then it booted in OS, now developer mode still detected, only meet basic integrity, failed for device.

**Comment by changhuapeng** [comment]
Can you try the solutions listed in the FAQ on my XDA thread?

**Comment by Sucharek233** [comment]
The 2nd file works. Bootloader is now spoofed as locked. But I only pass basic+device. I do have a working TEE (or at least I think I do).
I do have Iconify and PixelXpert, so that might be a problem.
And PIF v16.0 passes basic+device and v16.1+v16.2 passes only basic, but after changing DEVICE_INITIAL_SDK_INT at also passes basic+device.
Still no strong though.
![Screenshot_20240620-084259_Key_Attestation](https://github.com/changhuapeng/FrameworkPatcherGO/assets/31042508/db6fa9be-84f6-40a4-b8e0-b312b5132903)
![Screenshot_20240620-084351_Momo](https://github.com/changhuapeng/FrameworkPatcherGO/assets/31042508/563dc374-8247-4f14-ad7c-f9927d84ad91)

**Comment by changhuapeng** [comment]
> Bootloader is now spoofed as locked. But I only pass basic+device. I do have a working TEE (or at least I think I do).
> I do have Iconify and PixelXpert, so that might be a problem.
> And PIF v16.0 passes basic+device and v16.1+v16.2 passes only basic, but after changing DEVICE_INITIAL_SDK_INT at also passes basic+device.
> Still no strong though.

That's the expected result from this module, strong integrity was never meant to be passed using the default software attestation keybox provided.
